version: '3.8'
services:
  database_blog:
    image: postgres
    container_name: database_blog
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
